
import {
  Store,
  Wine,
  Pizza,
  Coffee,
  UtensilsCrossed,
  Pencil,
  Sparkles,
  SprayCan,
  Laptop,
  Tag,
  ShoppingBag,
  Apple,
  Carrot,
  Shirt,
  Heart,
  Home,
  Book,
  Gift,
  Camera,
  Globe,
  Music,
  LucideIcon,
} from "lucide-react";

// Map of icon names to Lucide components for rendering
export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  Store,
  Wine,
  Pizza,
  Coffee,
  UtensilsCrossed,
  Pencil,
  Sparkles,
  SprayCan,
  Laptop,
  Tag,
  ShoppingBag,
  Apple,
  Carrot,
  Shirt,
  Heart,
  Home,
  Book,
  Gift,
  Camera,
  Globe,
  Music,
};

export const CATEGORY_ICONS = [
  { name: "Store", icon: Store },
  { name: "Wine", icon: Wine },
  { name: "Pizza", icon: Pizza },
  { name: "Coffee", icon: Coffee },
  { name: "UtensilsCrossed", icon: UtensilsCrossed },
  { name: "Pencil", icon: Pencil },
  { name: "Sparkles", icon: Sparkles },
  { name: "SprayCan", icon: SprayCan },
  { name: "Laptop", icon: Laptop },
  { name: "Tag", icon: Tag },
  { name: "ShoppingBag", icon: ShoppingBag },
  { name: "Apple", icon: Apple },
  { name: "Carrot", icon: Carrot },
  { name: "Shirt", icon: Shirt },
  { name: "Heart", icon: Heart },
  { name: "Home", icon: Home },
  { name: "Book", icon: Book },
  { name: "Gift", icon: Gift },
  { name: "Camera", icon: Camera },
  { name: "Globe", icon: Globe },
  { name: "Music", icon: Music },
];
